# Generated by Django 5.0.2 on 2024-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_desc',
            field=models.CharField(choices=[('Standard', 'desc'), ('Studio', 'desc'), ('Basic', 'desc')], max_length=10),
        ),
    ]
