# Generated by Django 5.0.2 on 2024-07-19 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_room_desc_alter_standard_shower_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='shower_type',
            field=models.CharField(choices=[('1', 'Shower'), ('2', 'Bath'), ('3', 'Combination Shower-Bath')], max_length=1),
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField()),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
    ]
