# Generated by Django 5.0.2 on 2024-07-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_standard_shower_type_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_desc',
            field=models.CharField(choices=[('Basic', 'desc'), ('Standard', 'desc'), ('Studio', 'desc')], max_length=10),
        ),
        migrations.AlterField(
            model_name='standard',
            name='shower_type',
            field=models.CharField(choices=[('2', 'Bath'), ('1', 'Shower'), ('3', 'Combination Shower-Bath')], max_length=1),
        ),
    ]
