# Generated by Django 5.0.2 on 2024-07-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_room_room_desc_alter_standard_shower_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='standard_ptr',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_desc',
            field=models.CharField(choices=[('Studio', 'desc'), ('Basic', 'desc'), ('Standard', 'desc')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Standard',
        ),
        migrations.DeleteModel(
            name='Studio',
        ),
    ]
