# Generated by Django 5.0.2 on 2024-07-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_room_room_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_desc',
            field=models.CharField(choices=[('Basic', 'desc'), ('Standard', 'desc'), ('Studio', 'desc')], max_length=10),
        ),
    ]
